/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.Pembeli;
import com.ConvertPembeliToObject;
import java.awt.CardLayout;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import AppPackage.AnimationClass;
import com.ConvertGameToObject;
import db.ConnectionManager;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import static view.LoginForm.a;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Faadlilah Ahmad Purwanto
 */
public final class MainFormStore extends javax.swing.JFrame {
    private final String url = "jdbc:mysql://localhost:3306/oop_game"; 
    private final String username = "root";       
    private final String password = "";
    public static Pembeli akun;
    
    AnimationClass ac = new AnimationClass();
    
    
    
    /**
     * Creates new form MainFormStore
     */
    public MainFormStore () {
        initComponents();
        setdataUser();
        setdataGame();
        slidershow();
        Component [] components = this.getContentPane().getComponents();
        for(Component component : components)
        {
            if(component instanceof JButton)
            {
                ((JButton) component).setUI(new BasicButtonUI());
                ((JButton) component).setFocusPainted(false);
            }
        }
        cl = (CardLayout)(pnlcard.getLayout());
    }
    public void slidershow(){
        new Thread(() -> {
            int nb = 0;
            try{
                while(true){
                    switch(nb){
                        case 0:
                            Thread.sleep(3000);
                            ac.jLabelXLeft(0, -500, 12, 10, img1);
                            ac.jLabelXLeft(500, 0, 12, 10, img2);
                            ac.jLabelXLeft(1000, 500, 12, 10, img3);
                            nb++;
                        case 1:
                            Thread.sleep(3000);
                            ac.jLabelXLeft(-500,-1000, 12, 10, img1);
                            ac.jLabelXLeft(0, -500, 12, 10, img2);
                            ac.jLabelXLeft(500, 0, 12, 10, img3);
                            nb++;
                        case 2:
                            Thread.sleep(3000);
                            ac.jLabelXRight(-1000, -500, 12, 10, img1);
                            ac.jLabelXRight(-500, 0, 12, 10, img2);
                            ac.jLabelXRight(0, 500, 12, 10, img3);
                            nb++;
                        case 3:
                            Thread.sleep(3000);
                            ac.jLabelXRight(-500, 0, 12, 10, img1);
                            ac.jLabelXRight(0, 500, 12, 10, img2);
                            ac.jLabelXRight(0, 500, 12, 10, img3);
                            nb=0;
                    }
                }
            }catch(Exception ex){
                
            }
        }).start();
            
        }
    
    private void setdataUser(){
        ConvertPembeliToObject cpto = new ConvertPembeliToObject();
        String[][] dataUser = cpto.getPembeli();
        tblpembeli.setModel(new javax.swing.table.DefaultTableModel(
                dataUser,
            new String [] {
                "ID","Username", "Password", "Nama", "Alamat", "Email", "No HP"
            }
        ));
    }
    
    private void setdataGame(){
        ConvertGameToObject cgto = new ConvertGameToObject();
        String[][] dataGame = cgto.getGame();
        tblgame.setModel(new javax.swing.table.DefaultTableModel(
                dataGame,
            new String [] {
                "ID","Judul", "Genre", "Harga"
            }
        ));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlside = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btngame = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnexit = new javax.swing.JButton();
        pnlcard = new javax.swing.JPanel();
        pblhome = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        pnlgame = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblgame = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsearch1 = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtjudul = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtgenre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtidgm = new javax.swing.JTextField();
        pnlpembayaran = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcart = new javax.swing.JTextArea();
        btnpesan = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        pnlpembeli = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpembeli = new javax.swing.JTable();
        btnback = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtdate = new javax.swing.JTextField();
        txtgm = new javax.swing.JTextField();
        txtpm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setDividerSize(1);

        pnlside.setBackground(new java.awt.Color(102, 102, 102));
        pnlside.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btngame.setBackground(new java.awt.Color(153, 153, 153));
        btngame.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btngame.setForeground(new java.awt.Color(51, 51, 51));
        btngame.setText("List Game");
        btngame.setBorder(null);
        btngame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btngame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btngame, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btngame, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlside.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_shop_100px_1.png"))); // NOI18N
        jLabel2.setText("ScrappShop");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pnlside.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 120));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-game-controller-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlside.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, 70));
        pnlside.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 10));

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        pnlside.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jSplitPane1.setLeftComponent(pnlside);

        pnlcard.setLayout(new java.awt.CardLayout());

        pblhome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tsushima.jpg"))); // NOI18N
        pblhome.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        img2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ff7.jpg"))); // NOI18N
        pblhome.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        img3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cyberpunk2077-fb.jpg"))); // NOI18N
        pblhome.add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlcard.add(pblhome, "cardhome");

        pnlgame.setBackground(new java.awt.Color(255, 153, 153));
        pnlgame.setForeground(new java.awt.Color(255, 255, 255));

        tblgame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Judul", "Genre", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgameMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblgame);
        if (tblgame.getColumnModel().getColumnCount() > 0) {
            tblgame.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Judul");

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cart");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Genre");

        txtsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearch1KeyReleased(evt);
            }
        });

        txtharga.setEditable(false);

        txtjumlah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtjumlahPropertyChange(evt);
            }
        });
        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjumlahKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Search Game by :");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Total");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Harga");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Jumlah");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Judul");

        txtjudul.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtjudulPropertyChange(evt);
            }
        });
        txtjudul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjudulKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Genre");

        txtgenre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtgenrePropertyChange(evt);
            }
        });
        txtgenre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgenreKeyReleased(evt);
            }
        });

        jButton1.setText("Lanjutkan Pembayaran");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlgameLayout = new javax.swing.GroupLayout(pnlgame);
        pnlgame.setLayout(pnlgameLayout);
        pnlgameLayout.setHorizontalGroup(
            pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlgameLayout.createSequentialGroup()
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlgameLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlgameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlgameLayout.createSequentialGroup()
                                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtgenre, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlgameLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlgameLayout.createSequentialGroup()
                                .addComponent(txtidgm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(pnlgameLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(5, 5, 5)
                                        .addComponent(txtsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(pnlgameLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlgameLayout.setVerticalGroup(
            pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlgameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlgameLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(pnlgameLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtidgm, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(pnlgameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );

        pnlcard.add(pnlgame, "cardgame");

        pnlpembayaran.setBackground(new java.awt.Color(102, 255, 204));
        pnlpembayaran.setForeground(new java.awt.Color(204, 255, 102));

        txtcart.setColumns(20);
        txtcart.setRows(5);
        jScrollPane3.setViewportView(txtcart);

        btnpesan.setText("Lakukan Pemesanan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Pembayaran");

        javax.swing.GroupLayout pnlpembayaranLayout = new javax.swing.GroupLayout(pnlpembayaran);
        pnlpembayaran.setLayout(pnlpembayaranLayout);
        pnlpembayaranLayout.setHorizontalGroup(
            pnlpembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpembayaranLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(pnlpembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpembayaranLayout.createSequentialGroup()
                        .addComponent(btnpesan)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpembayaranLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(259, 259, 259))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpembayaranLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );
        pnlpembayaranLayout.setVerticalGroup(
            pnlpembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpembayaranLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpesan)
                .addGap(106, 106, 106))
        );

        pnlcard.add(pnlpembayaran, "cardpembayaran");

        pnlpembeli.setBackground(new java.awt.Color(153, 204, 0));

        tblpembeli.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblpembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Password", "Nama", "Alamat", "Email", "No HP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblpembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpembeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpembeli);
        if (tblpembeli.getColumnModel().getColumnCount() > 0) {
            tblpembeli.getColumnModel().getColumn(0).setResizable(false);
        }

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_arrow_48px.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel7.setText("Username");

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel9.setText("Nama");

        txtNama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Alamat");

        txtAlamat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Email");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel12.setText("No HP");

        txtNo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel13.setText("ID");

        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Segoe UI", 2, 11)); // NOI18N
        txtID.setForeground(new java.awt.Color(255, 51, 51));
        txtID.setText("ID cannot be changed");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlpembeliLayout = new javax.swing.GroupLayout(pnlpembeli);
        pnlpembeli.setLayout(pnlpembeliLayout);
        pnlpembeliLayout.setHorizontalGroup(
            pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
            .addGroup(pnlpembeliLayout.createSequentialGroup()
                .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlpembeliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(btnCancel)
                        .addGap(37, 37, 37)
                        .addComponent(btnSimpan))
                    .addGroup(pnlpembeliLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl1))
                    .addGroup(pnlpembeliLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(27, 27, 27)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(31, 31, 31)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(51, 51, 51)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(55, 55, 55)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(49, 49, 49)
                                .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlpembeliLayout.setVerticalGroup(
            pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpembeliLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpembeliLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlpembeliLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12))
                            .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlpembeliLayout.createSequentialGroup()
                        .addGroup(pnlpembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnCancel))
                        .addGap(29, 29, 29))))
        );

        pnlcard.add(pnlpembeli, "cardpembeli");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtpm, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(txtgm)
                    .addComponent(txtdate))
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(txtgm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(txtpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        pnlcard.add(jPanel3, "card6");

        jSplitPane1.setRightComponent(pnlcard);

        background.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -7, 920, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(916, 553));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btngameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngameActionPerformed
        cl.show(pnlcard, "cardgame");
    }//GEN-LAST:event_btngameActionPerformed

    private void tblpembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpembeliMouseClicked
        int row = tblpembeli.getSelectedRow();
        String id = tblpembeli.getValueAt(row, 0).toString();
        String username = tblpembeli.getValueAt(row, 1).toString();
        String password = tblpembeli.getValueAt(row, 2).toString();
        String nama = tblpembeli.getValueAt(row, 3).toString();
        String alamat = tblpembeli.getValueAt(row, 4).toString();
        String email = tblpembeli.getValueAt(row, 5).toString();
        String no_hp = tblpembeli.getValueAt(row, 6).toString();
        txtID.setText(id);
        txtUsername.setText(username);
        txtPassword.setText(password);
        txtNama.setText(nama);
        txtAlamat.setText(alamat);
        txtEmail.setText(email);
        txtNo.setText(no_hp);
    }//GEN-LAST:event_tblpembeliMouseClicked

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        cl.show(pnlcard, "cardhome");
    }//GEN-LAST:event_btnbackActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        cl.show(pnlcard, "cardhome");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        JOptionPane.showMessageDialog(null,"Terimakasih" );
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void tblgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgameMouseClicked
        int row = tblgame.getSelectedRow();
        String id_game = tblgame.getValueAt(row, 0).toString();
        String judul = tblgame.getValueAt(row, 1).toString();
        String genre = tblgame.getValueAt(row, 2).toString();
        String strharga = tblgame.getValueAt(row, 3).toString();
        txtharga.setText(strharga);
        int d = Integer.parseInt(strharga);
        txtjudul.setText(judul);
        txtgenre.setText(genre);
        txtidgm.setText(id_game);
    }//GEN-LAST:event_tblgameMouseClicked

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
       String genre = txtsearch.getText();
       ConvertGameToObject cgto = new ConvertGameToObject();
       try{
           tblgame.setModel(DbUtils.resultSetToTableModel(cgto.SearchTextGenre(genre)));
       }catch (SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearch1KeyReleased
        String judul = txtsearch1.getText();
       ConvertGameToObject cgto = new ConvertGameToObject();
       try{
           tblgame.setModel(DbUtils.resultSetToTableModel(cgto.SearchTextJudul(judul)));
       }catch (SQLException e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_txtsearch1KeyReleased

    private void txtjumlahPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtjumlahPropertyChange

    }//GEN-LAST:event_txtjumlahPropertyChange

    private void txtjumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyReleased
        String c = txtjumlah.getText();
        int d =Integer.parseInt(c);
        String e = txtharga.getText();
        int f =Integer.valueOf(e);
        int g = d * f;
        String h = Integer.toString(g);
        txttotal.setText(h);
    }//GEN-LAST:event_txtjumlahKeyReleased

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String strid_pembeli = txtID.getText();
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String nama = txtNama.getText();
        String alamat = txtAlamat.getText();
        String email = txtEmail.getText();
        String no_hp = txtNo.getText();
        int id_pembeli = Integer.parseInt(strid_pembeli);
        Pembeli pm = new Pembeli(id_pembeli, username, password, nama, alamat, email, no_hp);
        exec.ExecutePembeli ePembeli = new exec.ExecutePembeli();
        int hasil = ePembeli.updatepembeli(pm);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Profile berhasil di ubah");
            setdataUser();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data gagal di ubah");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        txtID.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtEmail.setText("");
        txtNo.setText("");
        JOptionPane.showMessageDialog(null, "Profile batal di ubah");
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtjudulPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtjudulPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulPropertyChange

    private void txtjudulKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjudulKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulKeyReleased

    private void txtgenrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtgenrePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenrePropertyChange

    private void txtgenreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgenreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenreKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate now = LocalDate.now();
        cl.show(pnlcard, "cardpembayaran");
        String judul = txtjudul.getText();
        String genre = txtgenre.getText();
        String harga = txtharga.getText();
        String jumlah = txtjumlah.getText();
        String total = txttotal.getText();
        txtcart.append("Game yang dipilih : "+judul+ "\n");
        txtcart.append("Bergenre : "+genre+ "\n");
        txtcart.append("Harga Game : "+harga+ "\n");
        txtcart.append("Jumlah : "+jumlah+" buah"+ "\n");
        txtcart.append("Total yang harus dibayar : "+total+ "\n");
        txtcart.append("Tanggal Transaksi "+dtf.format(now)+"\n");
        txtcart.append("-------------------------------------\n");
        txtcart.append("PEMBAYARAN  \n");
        txtcart.append("Silahkan untuk melakukan pembayaran dengan metode berikut : \n");
        txtcart.append("BCA 000829102938 a.n Scappshop \n");
        txtcart.append("OVO 081299738292 a.n Scappshop \n");
        txtcart.append("GOPAY 081299738292 a.n Scappshop \n");
        
        txtcart.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDate now = LocalDate.now();
        int hasil = 0;
        txtdate.setText(dtf.format(now));
        String id_game = txtidgm.getText();
        String id_pembeli = txtID.getText();
        String tgl_transaksi = txtdate.getText();  
        ConnectionManager con = new ConnectionManager();
        Connection conn = con.logOn();
        String sql;
        sql = "insert into transaksi (tgl_transaksi,id_game,id_pembeli) values(?,?,?)";
        PreparedStatement pst;
        ResultSet rs;
        try{          
            pst = con.logOn().prepareStatement(sql);
            pst.setString(1, tgl_transaksi);           
            pst.setString(2, id_game);           
            pst.setString(3, id_pembeli);           
            if(pst.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null,"Terimakasih Telah berbelanja di Scrappshop");
                System.exit(0);
            }
            
            
        }
        catch(HeadlessException | SQLException e){
            Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnpesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFormStore().setVisible(true);
        });
    }
    CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btngame;
    private javax.swing.JButton btnpesan;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JPanel pblhome;
    private javax.swing.JPanel pnlcard;
    private javax.swing.JPanel pnlgame;
    private javax.swing.JPanel pnlpembayaran;
    private javax.swing.JPanel pnlpembeli;
    private javax.swing.JPanel pnlside;
    private javax.swing.JTable tblgame;
    private javax.swing.JTable tblpembeli;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextArea txtcart;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtgenre;
    private javax.swing.JTextField txtgm;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidgm;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtpm;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsearch1;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
